name: Build and Deploy

on:
  push:
    paths:
      - 'app/**'
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual workflow run'
        required: false
        default: 'Manual trigger'

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker-hub
    outputs:
      image_tag: ${{ steps.image_tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Generate Image Tag
        id: image_tag
        run: echo "tag=v${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ env.tag }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Pastikan kita mendapatkan seluruh riwayat commit

      - name: Pull latest changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull --rebase origin main

      - name: Update deployment file
        run: |
          NEW_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ needs.build.outputs.image_tag }}"
          sed -i "s|image: .*/podname:.*|image: ${NEW_IMAGE}|" k8s/app/deployment.yaml

      - name: Auto Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update image tag to ${{ needs.build.outputs.image_tag }}"
          file_pattern: 'k8s/app/deployment.yaml'
          push_options: '--force'  
